org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true

# Use the JDK installed on this Linux development machine.
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
